<a href="https://colab.research.google.com/github/manikantadon/Iris-Flower-Project/blob/master/Numpy_LearningPath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Tutorial

***what is numpy ?***
NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

NumPy provides various powerful data structures, implementing multi-dimensional arrays and matrices. These data structures are used for the optimal computations regarding arrays and matrices.

***There are the following advantages of using NumPy for data analysis.***

1) NumPy performs array-oriented computing.
2)It performs scientific computations.
3) It is capable of performing Fourier Transform and reshaping the data stored in multidimensional arrays.
4) NumPy provides the in-built functions for linear algebra and random number generation.

**NumPy Ndarray**

Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.

Each element of the Array object contains the same size in the memory.

***creating ndarray***

In [ ]:
import numpy as np
array = np.array
array

<function numpy.array>

In [ ]:
print(array)

<built-in function array>


**syntax**∇  
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)∇

object	It represents the collection object. It can be a list, tuple, dictionary, set, etc.

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
print(a)

[1 2 3 4]


In [ ]:
b = np.array([1,2,3,4],complex)
b

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
floats = np.array([1,2,3,4],float)
floats

array([1., 2., 3., 4.])

In [ ]:
check_dimension = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("No. of dimensions ",check_dimension.ndim)
print("printing the arra check_dimension \n",check_dimension)

No. of dimensions  2
printing the arra check_dimension 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Finding the size of each array element**∇   

The itemsize function is used to get the size of each array item. It returns the number of bytes taken by each array element.

In [ ]:
#finding the size of each item in the array
import numpy as np
a = np.array([[1,2,3]])
print("Each item contains",a.itemsize,"bytes")

Each item contains 8 bytes


In [ ]:
multi_dimension = np.array([[1,2,3,4],[5,6,7,8]])
print("Each item contains",multi_dimension.itemsize,"bytes")

Each item contains 8 bytes


**Finding size and shape of an Array**

In [ ]:
print("size is",a.size,"\nshape is",a.shape)
print(multi_dimension.size,"\n",multi_dimension.shape)

size is 3 
shape is (1, 3)
8 
 (2, 4)


**Slicing the Array**

In [ ]:
print(a[0],a[0,1],a[:,:])

[1 2 3] 2 [[1 2 3]]


In [ ]:
print(multi_dimension[:,:],"\n",multi_dimension[:,0])

[[1 2 3 4]
 [5 6 7 8]] 
 [1 5]


In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a[:,1] # All rows with column 1

array([2, 5, 8])

****LineSpace****

The Linspace function returns series of evenly spaced values over the given interval

In [11]:
Linspace_interval = np.linspace(1,4,10)
Linspace_interval

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

** Max() Min() Sum() functions **

In [12]:
print(a.max(),a.min(),a.sum())

9 1 45


**square root and standard deviation**

In [18]:
np.sqrt(a) # Square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [19]:
np.std(a) # Standard deviation

2.581988897471611

***Arithmetic operations on ndarrays***

In [22]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
a+b # a-b All zeros a/b , a*b


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

**Array concatenation**

The numpy provides us with the vertical stacking and horizontal stacking which allows us to concatenate two multi-dimensional arrays vertically or horizontally.

In [31]:
verticalConcat = np.vstack((a,b))
HorizontalConcat = np.hstack((a,b))
print(verticalConcat,"\n\n",HorizontalConcat)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [32]:
# Functions
print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((2)):\n", np.eye((2))) # identity matrix
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.89450391 0.31480867]
 [0.48341226 0.92709599]]
